# Generated by Django 5.1.4 on 2025-01-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('VCode', models.TextField()),
                ('VName', models.TextField()),
                ('VNameUrdu', models.TextField()),
                ('Address1', models.TextField()),
                ('Address2', models.TextField()),
                ('AddressUrdu1', models.TextField()),
                ('AddressUrdu2', models.TextField()),
                ('SortOrder', models.IntegerField()),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('IsActive', models.BooleanField(default=True)),
                ('UID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField()),
            ],
        ),
    ]
