# Generated by Django 5.1.4 on 2025-01-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0005_allowded_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowdedcat',
            name='VName',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
