# Generated by Django 5.1.4 on 2025-02-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0006_allowdedcat_vname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('VCode', models.TextField()),
                ('VName', models.TextField()),
                ('TimeIn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeOut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RestTimeFrom', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RestTimeTo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('WorkingHrs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RelaxTime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MinAttTime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MinHDTime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeInRamazan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeOutRamazan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RestTimeFromRamazan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RestTimeToRamazan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('WorkingHrsRamazan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RelaxTimeRamazan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MinAttTimeRamazan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MinHDTimeRamazan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsDayLight', models.BooleanField(default=True)),
                ('DayLightFrom', models.DateTimeField()),
                ('DayLightTo', models.DateTimeField()),
                ('TimeInDayLight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeOutDayLight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RestTimeFromDayLight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RestTimeToDayLight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsRoster', models.BooleanField(default=True)),
                ('IsSecurity', models.BooleanField(default=True)),
                ('SaturdayHalfTime', models.BooleanField(default=True)),
                ('LocationID', models.IntegerField()),
                ('IsActive', models.BooleanField(default=True)),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField()),
            ],
        ),
    ]
