# Generated by Django 5.1.4 on 2025-02-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0007_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryIncrement',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('VName', models.TextField()),
                ('VNo', models.TextField()),
                ('VDate', models.DateField()),
                ('EmpID', models.DecimalField(decimal_places=0, max_digits=18)),
                ('DateFrom', models.DateField()),
                ('CurrentSalary', models.DecimalField(decimal_places=0, max_digits=18)),
                ('IncrementAmount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('IncrementSpecial', models.DecimalField(decimal_places=0, max_digits=18)),
                ('IncrementPromotional', models.DecimalField(decimal_places=0, max_digits=18)),
                ('FirstAmount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('CurrentDesgID', models.IntegerField()),
                ('NewDesgID', models.IntegerField()),
                ('IsPosted', models.IntegerField()),
                ('PostedBy', models.IntegerField()),
                ('PostedDate', models.DateTimeField()),
                ('IsCanceled', models.IntegerField()),
                ('CanceledBy', models.IntegerField()),
                ('CanceledDate', models.DateTimeField()),
                ('IsActive', models.BooleanField(default=True)),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField()),
            ],
        ),
    ]
