# Generated by Django 5.1.4 on 2025-02-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0008_salaryincrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrement',
            name='CanceledBy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salaryincrement',
            name='CanceledDate',
            field=models.DateTimeField(null=True),
        ),
    ]
