# Generated by Django 5.1.4 on 2025-02-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0009_alter_salaryincrement_canceledby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAllowDed',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('VName', models.TextField()),
                ('VNo', models.TextField()),
                ('VDate', models.DateField()),
                ('EmpID', models.DecimalField(decimal_places=0, max_digits=18)),
                ('RefNo', models.TextField()),
                ('AllowDedID', models.IntegerField()),
                ('Qty', models.IntegerField()),
                ('Amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('AccountID', models.IntegerField(null=True)),
                ('ChequeNo', models.TextField(null=True)),
                ('ChequeDate', models.DateTimeField(null=True)),
                ('FinancialYearID', models.IntegerField(null=True)),
                ('IsApproved', models.IntegerField()),
                ('ApprovedBy', models.IntegerField()),
                ('ApprovedDate', models.DateTimeField()),
                ('IsPosted', models.IntegerField()),
                ('PostedBy', models.IntegerField()),
                ('PostedDate', models.DateTimeField()),
                ('IsActive', models.BooleanField(default=True)),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField()),
            ],
        ),
    ]
