# Generated by Django 5.1.4 on 2025-02-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0012_alter_ramazan_tranzdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='LocationID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='Tranzdatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Tranzdatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='Tranzdatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
