# Generated by Django 5.1.4 on 2025-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0014_attotmonth_emplocationtransfer_employee_employeetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecPage',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('SrlNo', models.TextField()),
                ('VName', models.TextField()),
                ('RoutingPage', models.TextField()),
                ('MenuLevel', models.IntegerField()),
                ('Parentid', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecRole',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('VName', models.TextField()),
                ('IsActive', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecRolePage',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleID', models.IntegerField()),
                ('PageID', models.IntegerField()),
                ('IsView', models.IntegerField()),
                ('IsInsert', models.IntegerField()),
                ('IsUpdate', models.IntegerField()),
                ('IsDelete', models.IntegerField()),
                ('IsBackdate', models.IntegerField()),
                ('IsPrint', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecUser',
            fields=[
                ('UserID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Userfullname', models.TextField()),
                ('Userlogin', models.TextField()),
                ('Userpassword', models.TextField(max_length=50)),
                ('EmployeeID', models.DecimalField(decimal_places=0, max_digits=18)),
                ('AllowAudit', models.IntegerField()),
                ('AllowActual', models.IntegerField()),
                ('IsManager', models.IntegerField()),
                ('IsAdmin', models.IntegerField()),
                ('IsSystemAdmin', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecUserCompany',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecUserLocation',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('LocationID', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecUserPage',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('IncludeExclude', models.IntegerField()),
                ('UserID', models.IntegerField()),
                ('PageID', models.IntegerField()),
                ('IsView', models.IntegerField()),
                ('IsInsert', models.IntegerField()),
                ('IsUpdate', models.IntegerField()),
                ('IsDelete', models.IntegerField()),
                ('IsBackdate', models.IntegerField()),
                ('IsPrint', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecUserRole',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('RoleID', models.IntegerField()),
                ('IsActive', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
