# Generated by Django 5.1.4 on 2025-05-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0015_secpage_secrole_secrolepage_secuser_secusercompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ActualSalary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EOBINoAct',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='MachineCode',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ManagerSalary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='employee',
            name='OTRate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='OTRateOFF',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='OldCode',
            field=models.TextField(default='-'),
        ),
    ]
