# Generated by Django 5.1.4 on 2025-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0016_alter_employee_actualsalary_alter_employee_eobinoact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ActualSalary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='MachineCode',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ManagerSalary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='employee',
            name='OTRate',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='OTRateOFF',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='OldCode',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ReplacementOf',
            field=models.TextField(blank=True),
        ),
    ]
