# Generated by Django 5.1.4 on 2025-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0018_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ProbitionStatus',
            field=models.TextField(blank=True),
        ),
    ]
