# Generated by Django 5.1.4 on 2025-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0020_alter_employee_bankaccountno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplocationtransfer',
            name='VNo',
            field=models.TextField(blank=True),
        ),
    ]
