# Generated by Django 5.1.4 on 2025-05-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0021_alter_emplocationtransfer_vno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrement',
            name='CurrentDesgID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryincrement',
            name='IsCanceled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryincrement',
            name='IsPosted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryincrement',
            name='NewDesgID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryincrement',
            name='PostedBy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryincrement',
            name='PostedDate',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='salaryincrement',
            name='VName',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salaryincrement',
            name='VNo',
            field=models.TextField(blank=True),
        ),
    ]
