# Generated by Django 5.1.4 on 2025-05-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0022_alter_salaryincrement_currentdesgid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryallowded',
            name='VName',
            field=models.TextField(blank=True),
        ),
    ]
