# Generated by Django 5.1.4 on 2025-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0023_alter_salaryallowded_vname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryallowded',
            name='Qty',
            field=models.IntegerField(default=0),
        ),
    ]
