# Generated by Django 5.1.4 on 2025-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0024_alter_salaryallowded_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryallowded',
            name='ApprovedBy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salaryallowded',
            name='ApprovedDate',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='salaryallowded',
            name='IsApproved',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salaryallowded',
            name='IsPosted',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salaryallowded',
            name='PostedBy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salaryallowded',
            name='PostedDate',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='salaryallowded',
            name='RefNo',
            field=models.TextField(default='-'),
        ),
    ]
