# Generated by Django 5.1.4 on 2025-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0026_alter_salaryloan_approvedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryGratuity',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('VName', models.TextField(blank=True)),
                ('VNo', models.TextField()),
                ('VDate', models.DateField()),
                ('DemandTill', models.DateField()),
                ('PaidTill', models.DateField()),
                ('PaidOld', models.DateField()),
                ('EmpID', models.DecimalField(decimal_places=0, max_digits=18)),
                ('DueAmount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('PaidAmount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('NewAmount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('GYearsEffected', models.IntegerField(null=True)),
                ('GYears', models.IntegerField(null=True)),
                ('GMonths', models.IntegerField(null=True)),
                ('isApproved', models.IntegerField(default=1)),
                ('isPosted', models.IntegerField(default=1)),
                ('PostedDate', models.DateTimeField(default='1900-01-01')),
                ('PostedBy', models.IntegerField(default=1)),
                ('CompanyBankID', models.IntegerField(null=True)),
                ('ChequeNo', models.TextField(null=True)),
                ('ChequeDate', models.DateTimeField(null=True)),
                ('FinancialYearID', models.IntegerField(null=True)),
                ('isCancel', models.IntegerField(default=True)),
                ('UID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
