# Generated by Django 5.1.4 on 2025-05-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0027_salarygratuity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTrial',
            fields=[
                ('EmpID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpCode', models.TextField()),
                ('EName', models.TextField()),
                ('FName', models.TextField()),
                ('DeptID', models.IntegerField()),
                ('ShiftID', models.IntegerField()),
                ('DOJ', models.DateTimeField()),
                ('DOB', models.DateTimeField()),
                ('Address', models.TextField(blank=True)),
                ('Reference', models.TextField(blank=True)),
                ('TelePhone', models.TextField(blank=True)),
                ('NIC', models.TextField()),
                ('ClosingDate', models.DateTimeField(default='1900-01-01')),
                ('ClosingStatus', models.TextField(blank=True)),
                ('ClosingRemarks', models.TextField(blank=True)),
                ('LocationID', models.IntegerField()),
                ('EmpIDOld', models.DecimalField(decimal_places=0, max_digits=18)),
                ('EmpCodeOld', models.TextField()),
                ('MachineCode', models.TextField(blank=True)),
                ('ActualEmpID', models.DecimalField(decimal_places=0, max_digits=18)),
                ('HireType', models.TextField()),
                ('UID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.IntegerField()),
            ],
        ),
    ]
