# Generated by Django 5.1.4 on 2025-05-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0028_employeetrial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetrial',
            name='ActualEmpID',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='employeetrial',
            name='EmpCode',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='employeetrial',
            name='EmpCodeOld',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='employeetrial',
            name='EmpIDOld',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='employeetrial',
            name='LocationID',
            field=models.IntegerField(default=0),
        ),
    ]
