# Generated by Django 5.1.4 on 2025-05-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0029_alter_employeetrial_actualempid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeetrial',
            old_name='EmpID',
            new_name='VID',
        ),
    ]
