# Generated by Django 5.1.4 on 2025-06-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0030_rename_empid_employeetrial_vid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttLeaveSpecial',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('VName', models.TextField()),
                ('VNo', models.TextField()),
                ('EmpID', models.DecimalField(decimal_places=0, max_digits=18)),
                ('VDate', models.DateTimeField()),
                ('LeaveTypeID', models.IntegerField()),
                ('ContactNumber', models.TextField()),
                ('IsApproved', models.IntegerField(default=0)),
                ('ApprovedBy', models.IntegerField(default=0)),
                ('ApprovedDate', models.DateTimeField(default='1900-01-01')),
                ('IsPosted', models.IntegerField(default=0)),
                ('PostedBy', models.IntegerField(default=0)),
                ('PostedDate', models.DateTimeField(default='1900-01-01')),
                ('isSys', models.IntegerField(default=1)),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
