# Generated by Django 5.1.4 on 2025-06-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0032_alter_attleavespecial_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attleave',
            name='ApprovedBy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attleave',
            name='ApprovedDate',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='attleave',
            name='ContactNumber',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='attleave',
            name='IsApproved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attleave',
            name='IsPosted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attleave',
            name='PostedBy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attleave',
            name='PostedDate',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='attleave',
            name='isSys',
            field=models.IntegerField(default=1),
        ),
    ]
