# Generated by Django 5.1.4 on 2025-06-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0033_alter_attleave_approvedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attleave',
            name='ShiftID',
            field=models.IntegerField(default=0),
        ),
    ]
