# Generated by Django 5.1.4 on 2025-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0034_alter_attleave_shiftid'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarygratuity',
            name='DemandDate',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
