# Generated by Django 5.1.4 on 2025-06-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0035_salarygratuity_demanddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarygratuity',
            name='BasicSalary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salarygratuity',
            name='PaidOn',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
