# Generated by Django 5.1.4 on 2025-06-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0037_employeeleavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavebalance',
            name='EmpID',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=18),
            preserve_default=False,
        ),
    ]
