# Generated by Django 5.1.4 on 2025-06-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0038_employeeleavebalance_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attotmonth',
            name='CanceledBy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attotmonth',
            name='CanceledDate',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='attotmonth',
            name='IsCanceled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attotmonth',
            name='IsPosted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attotmonth',
            name='PostedBy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attotmonth',
            name='PostedDate',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
