# Generated by Django 5.1.4 on 2025-06-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0039_attotmonth_canceledby_attotmonth_canceleddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttLeaveDepartment',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('VName', models.TextField()),
                ('DeptID', models.IntegerField()),
                ('DateFrom', models.DateField()),
                ('DateTo', models.DateField()),
                ('LeaveTypeID', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('LocationID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
