# Generated by Django 5.1.4 on 2025-06-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0040_attleavedepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttExemptLate',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.DecimalField(decimal_places=0, max_digits=18)),
                ('DeptID', models.IntegerField()),
                ('LocationID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('VDate', models.DateField()),
                ('VName', models.TextField()),
                ('IsPosted', models.IntegerField()),
                ('PostedBy', models.IntegerField()),
                ('PostedDate', models.DateField()),
                ('IsCancel', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
