# Generated by Django 5.1.4 on 2025-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0042_alter_attexemptlate_isposted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attexemptlate',
            name='IsCancel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attot',
            name='VNo',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='attotmonth',
            name='VNo',
            field=models.TextField(default='-'),
        ),
    ]
