# Generated by Django 5.1.4 on 2025-06-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0044_alter_shift_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DOJ',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DOJAct',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DOL',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DOLAct',
            field=models.DateField(),
        ),
    ]
