# Generated by Django 5.1.4 on 2025-06-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsmodel', '0045_alter_employee_dob_alter_employee_doj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttRoster',
            fields=[
                ('VID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('VName', models.TextField()),
                ('VDate', models.DateField()),
                ('EmpID', models.DecimalField(decimal_places=0, max_digits=18)),
                ('ShiftID', models.IntegerField()),
                ('IsOff', models.IntegerField()),
                ('LocationID', models.IntegerField(default=0)),
                ('UID', models.IntegerField()),
                ('CompanyID', models.IntegerField()),
                ('Tranzdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
