
from django.urls import path
from emsmodel import views

urlpatterns = [
    path('dummy/', views.DummyAPI.as_view()),
    # path('get_company/', views.get_company),
    path('company/', views.CompanyAPI.as_view()),
    path('department/', views.DepartmentAPI.as_view()),
    path('departmentGroup/', views.DepartmentGroupAPI.as_view()),
    path('location/', views.LocationAPI.as_view()),
    path('location/', views.LocationAPI.as_view()),
    path('designation/', views.DesignationAPI.as_view()),
    path('grade/', views.GradeAPI.as_view()),
    path('bank/', views.BankAPI.as_view()),
    path('allowDedCat/', views.AllowDedCatAPI.as_view()),
    path('allowDed/', views.AllowDedAPI.as_view()),    
    path('allowDedGroup/', views.AllowDedGroupAPI.as_view()),
    path('allowDedCatByName/', views.AllowanceDedCatByNameAPI.as_view()),
    path('allowDedByCat/', views.AllowanceDedByCatAPI.as_view()),
    path('attCode/', views.AttCodeAPI.as_view()),
    path('attGroup/', views.AttGroupAPI.as_view()),
    path('ramazan/', views.RamazanAPI.as_view()),
    path('holiday/', views.HolidayAPI.as_view()),
    path('leaveBalance/', views.LeaveBalanceAPI.as_view()),
    path('leaveType/', views.LeaveTypeAPI.as_view()),
    path('shift/', views.ShiftAPI.as_view()),
    path('salaryIncrement/', views.SalaryIncrementAPI.as_view()),
    path('salaryAllowDed/', views.SalaryAllowDedAPI.as_view()),
    path('salaryLoan/', views.SalaryLoanAPI.as_view()),
    path('salaryLoanDeduction/', views.SalaryLoanDeductionAPI.as_view()),
    path('attMain/', views.AttMainAPI.as_view()),
    path('employeeLast10AttRecord/', views.EmployeeLast10AttRecordsAPI.as_view()),
    path('attClosingDay/', views.AttClosingDayAPI.as_view()),
    path('attLeave/', views.AttLeaveAPI.as_view()),
    path('attOT/', views.AttOTAPI.as_view()),
    path('attOTMonth/', views.AttOTMonthAPI.as_view()),
    path('salaryType/', views.SalaryTypeAPI.as_view()),
    path('employeeType/', views.EmployeeTypeAPI.as_view()),
    path('gender/', views.GenderAPI.as_view()),
    path('religion/', views.ReligionAPI.as_view()),
    path('status/', views.StatusAPI.as_view()),
    path('empLocationTransfer/', views.EmpLocationTransferAPI.as_view()),
    path('employee/', views.EmployeeAPI.as_view()),
    path('secUser/', views.SecUserAPI.as_view()),
    path('secRole/', views.SecRoleAPI.as_view()),
    path('secPage/', views.SecPageAPI.as_view()),
    path('secRolePage/', views.SecRolePageAPI.as_view()),
    path('secUserCompany/', views.SecUserCompanyAPI.as_view()),
    path('secUserLocation/', views.SecUserLocationAPI.as_view()),
    path('secUserRole/', views.SecUserRoleAPI.as_view()),
    path('secUserPage/', views.SecUserPageAPI.as_view()),
    path('attEntry/', views.AttEntryAPI.as_view()),
    path('employeeSearch/', views.EmployeeSearchAPI.as_view()),
    path('attChange/', views.AttChangeAPI.as_view()),
    path('attSingle/', views.AttSingleAPI.as_view()),
    path('salaryAdvance/', views.SalaryAdvanceAPI.as_view()),
    path('localSale/', views.LocalSaleAPI.as_view()),
    path('salaryGratuity/', views.SalaryGratuityAPI.as_view()),
    path('employeeTrial/', views.EmployeeTrialAPI.as_view()),
    path('getTypeByAllowDedId/', views.GetTypeByAllowDedIdAPI.as_view()),
    path('attLeaveType/', views.AttLeaveTypeAPI.as_view()),
    path('attLeaveSpecial/', views.AttLeaveSpecialAPI.as_view()),
    path('removeExtraAttendance/', views.RemoveExtraAttendanceAPI.as_view()),
    path('employeeLeaveBalance/', views.EmployeeLeaveBalanceAPI.as_view()),
    path('attOTFillGrid/', views.AttOTFillGridAPI.as_view()),
    path('attOTMonthFillGrid/', views.AttOTMonthFillGridAPI.as_view()),
    path('getEmployeeGratuityDetail/', views.GetEmployeeGratuityDetailAPI.as_view()),
    path('employeeReport/', views.EmployeeReportsAPI.as_view()),
    path('attLeaveDepartment/', views.AttLeaveDepartmentAPI.as_view()),
    path('attExemptLate/', views.AttExemptLateAPI.as_view()),
    path('rptAttDailyUnposted/', views.RptATTDailyUnpostedAPI.as_view()),
    path('rptAttDailyPosted/', views.RptATTDailyPostedAPI.as_view()),
    path('rptAttDailyLate/', views.RptATTDailyLateAPI.as_view()),
    path('rptAttDailyAB/', views.RptATTDailyABAPI.as_view()),
    path('rptAttMonthStatus/', views.RptATTMonthStatusAPI.as_view()),
    path('rptATTMonthSummary/', views.RptATTMonthSummaryAPI.as_view()),
    path('rptATTMonthAttendance/', views.RptATTMonthAttendanceAPI.as_view()),
    path('getRosterDepartment/', views.GetRosterDepartmentAPI.as_view()),
    path('rptATTMonthAB/', views.RptATTMonthABAPI.as_view()),
    path('rptATTMonthLeave/', views.RptATTMonthLeaveAPI.as_view()),
    path('attRoster/', views.AttRosterAPI.as_view()),
    path('getRosterShift/', views.GetRosterShiftAPI.as_view()),
    path('rptMonthSalarySheet/', views.RptMonthSalarySheetAPI.as_view()),
    path('rptOverTimeSheet/', views.RptOverTimeSheetAPI.as_view()),
    path('rptOverTimeSheetSummary/', views.RptOverTimeSheetSummaryAPI.as_view()),
    path('rptFinalSettlement/', views.RptFinalSettlementAPI.as_view()),
    path('RptSalaryEmployee/', views.RptSalaryEmployeeAPI.as_view()),
    path('rptMonthSalarySummary/', views.RptMonthSalarySummaryAPI.as_view()),
    path('attEntryRosterMonth/', views.AttEntryRosterMonthAPI.as_view()),
    path('paymentPlanFillGrid/', views.PaymentPlanFillGridAPI.as_view()),
    path('rptMonthSalaryDeduction/', views.RptMonthSalaryDeductionAPI.as_view()),
    path('rptMonthSalaryDeductionSum/', views.RptMonthSalaryDeductionSumAPI.as_view()),
    path('getddlLocation/', views.GetddlLocationAPI.as_view()),
    path('login/', views.LoginAPI.as_view()),
    # path('savePaymentPlan/', views.SavePaymentPlanAPI.as_view()),
    
] 